apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Backend.ID }}-run"
  # {{- if .Backend.Namespace}}
  namespace: "{{.Backend.Namespace}}"
  # {{- end }}
  labels:
    woodpecker: "true"
    woodpecker-run: "{{.Backend.ID}}"
spec:
  podSelector:
    matchLabels:
      woodpecker-run: "{{.Backend.ID}}"
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              woodpecker-run: "{{.Backend.ID}}"
