apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Run.ID }}-run"
  # {{- if .Run.Namespace}}
  namespace: "{{.Run.Namespace}}"
  # {{- end }}
  labels:
    woodpecker: "true"
    woodpecker-run: "{{.Run.ID}}"
spec:
  podSelector:
    matchLabels:
      woodpecker-run: "{{.Run.ID}}"
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              woodpecker-run: "{{.Run.ID}}"
