apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .JobName }}"
  # {{- if .Engine.Namespace}}
  namespace: "{{.Engine.Namespace}}"
  # {{- end }}
  labels:
    woodpecker: "true"
    woodpecker-job: "true"
    jobid: "{{.JobID}}"
    app: "{{.Engine.ID}}"
spec:
  # Number of times to run is one.
  backoffLimit: 0
  template:
    metadata:
      labels:
        woodpecker: "true"
        woodpecker-pod: "true"
        jobid: "{{.JobID}}"
        app: "{{.Engine.ID}}"
    spec:
      restartPolicy: Never
      containers:
        - name: runner
          image: "{{ .Step.Image }}"
          # {{- if .Step.WorkingDir }}
          workingDir: "{{ .Step.WorkingDir }}"
          # {{- end }}
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              echo "$CI_SCRIPT" | base64 -d
              echo 
              echo
              {{ .ShellCommand }}
          # {{- if .HasEnvironmentVariables }}
          env:
            # {{- range $env := .EnvironmentVariables }}
            - name: "{{- $env.Key -}}"
              value: "{{- $env.Value -}}"
            # {{- end }}
          # {{- end }}
          resources: {}
