skip_clone: true

# TODO: test bad image (image pull backoff)
runner_image: &runner_image artprod.dev.bloomberg.com/sdae/woodpecker/runners/ubuntu20:0.0.3
dind_image: &dind_image artprod.dev.bloomberg.com/sdae/docker:0.2.0

pipeline:
  first:
    image: *runner_image
    commands:
      - echo "first to run" >| loaded_message
      - cat loaded_message
  shared_test:
    image: *runner_image
    commands:
      - |
        echo "From first command: $(cat loaded_message)"
  comms_test:
    image: *runner_image
    commands:
      - cat /etc/hosts
      - echo; echo
      - nc -zv docker.service 2375
  docker_test:
    image: *dind_image
    environment:
      - DOCKER_HOST=docker.service:2375
      - TEST_IMAGE=artprod.dev.bloomberg.com/sdae/woodpecker/runners/ubuntu20:0.0.3
    commands:
      - docker ps
      - docker run -i --rm -v $PWD:/build $TEST_IMAGE ls

services:
  docker.service:
    image: *dind_image
    privileged: true
