skip_clone: true

# TODO: test bad image (image pull backoff)
runner_image: &runner_image artprod.dev.bloomberg.com/sdae/woodpecker/runners/ubuntu20:0.0.6
dind_image: &dind_image artprod.dev.bloomberg.com/sdae/docker:0.2.0

pipeline:
  test_error_image:
    image: not-an-image:latest
    commands:
      - lama
  first:
    image: *runner_image
    commands:
      - echo "first to run" >| loaded_message
      - cat loaded_message
  # fast_error:
  #   image: *runner_image
  #   commands:
  #     - |
  #       for i in $(seq 1 122); do
  #         echo "DUMMY $i";
  #       done
  #     - exit 22
  shared_test:
    image: *runner_image
    commands:
      - |
        echo "From first command: $(cat loaded_message)"
  comms_test:
    image: *runner_image
    commands:
      - nc -zv docker.service 2375 # Access detached
      - nc -zv artprod.dev.bloomberg.com 80 # Access external
      - nc -zv kbb-api.kube-bb.svc 80 # Access internal service.
services:
  docker.service:
    image: *dind_image
    privileged: true
  # logging.service:
  #   image: *runner_image
  #   commands:
  #     - |
  #       while true; do
  #         echo "Logging service: $(date)"
  #         sleep 1
  #       done
  #   privileged: true
