skip_clone: true

# TODO: test bad image (image pull backoff)
runner_image: &runner_image ubuntu:lastest
dind_image: &dind_image docker:lastest

pipeline:
  first:
    image: *runner_image
    commands:
      - echo "first to run" >| loaded_message
      - cat loaded_message
  shared_test:
    image: *runner_image
    commands:
      - |
        echo "From first command: $(cat loaded_message)"
  comms_test:
    image: *runner_image
    commands:
      - nc -zv docker.service 2375 # Access detached
      - nc -zv google.com 80 # Access external
services:
  docker.service:
    image: *dind_image
    privileged: true
  logging.service:
    image: *runner_image
    commands:
      - |
        while true; do
          echo "Logging service: $(date)"
          sleep 1
        done
    privileged: true
