skip_clone: true

pipeline:
  first:
    image: artprod.dev.bloomberg.com/ubuntu20:latest
    commands:
      - echo first
  second:
    image: artprod.dev.bloomberg.com/ubuntu20:latest
    commands:
      - echo second
